#include "common/metrics_collector.h"

#ifdef FENYUN_USE_PROMETHEUS
#include <prometheus/registry.h>
#include <prometheus/counter.h>
#include <prometheus/gauge.h>
#include <prometheus/histogram.h>
#include <prometheus/exposer.h>
#include <prometheus/client_metric.h>
#endif

#include <map>
#include <mutex>
#include <vector>
#include <chrono>
#include <atomic>
#include <string>

namespace fenyun {

struct MetricsCollector::Impl {
#ifdef FENYUN_USE_PROMETHEUS
    std::shared_ptr<prometheus::Registry> registry;
    std::unique_ptr<prometheus::Exposer> exposer;

    prometheus::Family<prometheus::Counter>* f_sensor_recv;
    prometheus::Family<prometheus::Counter>* f_sensor_valid;
    prometheus::Family<prometheus::Counter>* f_sensor_invalid;
    prometheus::Family<prometheus::Counter>* f_sensor_dropped;

    prometheus::Family<prometheus::Histogram>* f_sim_latency;
    prometheus::Family<prometheus::Counter>* f_sim_total;
    prometheus::Family<prometheus::Counter>* f_sim_errors;

    prometheus::Family<prometheus::Counter>* f_eval_total;
    prometheus::Family<prometheus::Histogram>* f_ahp_cr;

    prometheus::Family<prometheus::Counter>* f_alerts_total;
    prometheus::Family<prometheus::Counter>* f_mqtt_pub;
    prometheus::Family<prometheus::Counter>* f_mqtt_err;

    prometheus::Family<prometheus::Counter>* f_ch_write_ok;
    prometheus::Family<prometheus::Counter>* f_ch_write_fail;

    prometheus::Family<prometheus::Histogram>* f_http_latency;
    prometheus::Family<prometheus::Counter>* f_http_total;

    prometheus::Family<prometheus::Gauge>* f_queue_size;
#endif

    struct FallbackCounter { std::atomic<uint64_t> v{0}; };
    struct FallbackGauge { std::atomic<uint64_t> v{0}; };
    std::map<std::string, FallbackCounter*> fb_counters;
    std::map<std::string, FallbackGauge*> fb_gauges;
    std::mutex fb_mu;
};

MetricsCollector& MetricsCollector::instance() {
    static MetricsCollector inst;
    return inst;
}

MetricsCollector::MetricsCollector() : impl_(std::make_unique<Impl>()) {
#ifdef FENYUN_USE_PROMETHEUS
    impl_->registry = std::make_shared<prometheus::Registry>();

    impl_->f_sensor_recv = &prometheus::BuildCounter()
        .Name("fenyun_sensor_received_total")
        .Help("Total sensor samples received")
        .Register(*impl_->registry);
    impl_->f_sensor_valid = &prometheus::BuildCounter()
        .Name("fenyun_sensor_valid_total")
        .Help("Valid sensor samples passed validation")
        .Register(*impl_->registry);
    impl_->f_sensor_invalid = &prometheus::BuildCounter()
        .Name("fenyun_sensor_invalid_total")
        .Help("Invalid sensor samples rejected")
        .Register(*impl_->registry);
    impl_->f_sensor_dropped = &prometheus::BuildCounter()
        .Name("fenyun_sensor_dropped_total")
        .Help("Sensor samples dropped from queue (overflow)")
        .Register(*impl_->registry);

    impl_->f_sim_latency = &prometheus::BuildHistogram()
        .Name("fenyun_simulation_latency_ms")
        .Help("Impact simulation latency in ms")
        .Register(*impl_->registry);
    impl_->f_sim_total = &prometheus::BuildCounter()
        .Name("fenyun_simulation_total")
        .Help("Total simulations executed")
        .Register(*impl_->registry);
    impl_->f_sim_errors = &prometheus::BuildCounter()
        .Name("fenyun_simulation_errors_total")
        .Help("Simulations failed")
        .Register(*impl_->registry);

    impl_->f_eval_total = &prometheus::BuildCounter()
        .Name("fenyun_ahp_evaluations_total")
        .Help("Total AHP evaluations executed")
        .Register(*impl_->registry);
    impl_->f_ahp_cr = &prometheus::BuildHistogram()
        .Name("fenyun_ahp_consistency_ratio")
        .Help("AHP consistency ratio distribution")
        .Register(*impl_->registry);

    impl_->f_alerts_total = &prometheus::BuildCounter()
        .Name("fenyun_alerts_total")
        .Help("Alerts generated by level and type")
        .Register(*impl_->registry);
    impl_->f_mqtt_pub = &prometheus::BuildCounter()
        .Name("fenyun_mqtt_published_total")
        .Help("MQTT messages published successfully")
        .Register(*impl_->registry);
    impl_->f_mqtt_err = &prometheus::BuildCounter()
        .Name("fenyun_mqtt_errors_total")
        .Help("MQTT publish failures")
        .Register(*impl_->registry);

    impl_->f_ch_write_ok = &prometheus::BuildCounter()
        .Name("fenyun_clickhouse_rows_written_total")
        .Help("Rows written to ClickHouse")
        .Register(*impl_->registry);
    impl_->f_ch_write_fail = &prometheus::BuildCounter()
        .Name("fenyun_clickhouse_write_failures_total")
        .Help("ClickHouse write failures")
        .Register(*impl_->registry);

    impl_->f_http_latency = &prometheus::BuildHistogram()
        .Name("fenyun_http_request_latency_ms")
        .Help("HTTP request latency")
        .Register(*impl_->registry);
    impl_->f_http_total = &prometheus::BuildCounter()
        .Name("fenyun_http_requests_total")
        .Help("HTTP requests by method/path/status")
        .Register(*impl_->registry);

    impl_->f_queue_size = &prometheus::BuildGauge()
        .Name("fenyun_queue_approx_size")
        .Help("Approximate queue size by queue name")
        .Register(*impl_->registry);
#endif
}

MetricsCollector::~MetricsCollector() { stop(); }

bool MetricsCollector::start(uint16_t port, const std::string& bind_addr) {
    if (started_) return true;
#ifdef FENYUN_USE_PROMETHEUS
    try {
        std::string listen_addr = bind_addr + ":" + std::to_string(port);
        impl_->exposer = std::make_unique<prometheus::Exposer>(listen_addr, 1);
        impl_->exposer->RegisterCollectable(impl_->registry);
        started_ = true;
        return true;
    } catch (const std::exception& e) {
        (void)e;
        return false;
    }
#else
    (void)port; (void)bind_addr;
    return true;
#endif
}

void MetricsCollector::stop() {
#ifdef FENYUN_USE_PROMETHEUS
    impl_->exposer.reset();
#endif
    started_ = false;
}

#define DEFINE_COUNTER(fn, field) \
void MetricsCollector::fn(uint32_t n) { \
#ifdef FENYUN_USE_PROMETHEUS \
    impl_->field->Add({}).Increment(n); \
#else \
    (void)n; \
#endif \
}

DEFINE_COUNTER(inc_sensor_received, f_sensor_recv)
DEFINE_COUNTER(inc_sensor_valid, f_sensor_valid)
DEFINE_COUNTER(inc_sensor_invalid, f_sensor_invalid)
DEFINE_COUNTER(inc_sensor_dropped, f_sensor_dropped)
DEFINE_COUNTER(inc_simulation_total, f_sim_total)
DEFINE_COUNTER(inc_simulation_errors, f_sim_errors)
DEFINE_COUNTER(inc_evaluations_total, f_eval_total)
DEFINE_COUNTER(inc_mqtt_published, f_mqtt_pub)
DEFINE_COUNTER(inc_mqtt_errors, f_mqtt_err)
DEFINE_COUNTER(inc_clickhouse_write_fail, f_ch_write_fail)
#undef DEFINE_COUNTER

void MetricsCollector::observe_simulation_latency_ms(double ms) {
#ifdef FENYUN_USE_PROMETHEUS
    static const auto buckets = prometheus::Histogram::BucketBoundaries{
        0.1, 0.5, 1, 2, 5, 10, 25, 50, 100, 500
    };
    impl_->f_sim_latency->Add({}, buckets).Observe(ms);
#else
    (void)ms;
#endif
}

void MetricsCollector::observe_ahp_consistency_ratio(double cr) {
#ifdef FENYUN_USE_PROMETHEUS
    static const auto buckets = prometheus::Histogram::BucketBoundaries{
        0, 0.01, 0.05, 0.08, 0.1, 0.15, 0.2, 0.5, 1.0
    };
    impl_->f_ahp_cr->Add({}, buckets).Observe(cr);
#else
    (void)cr;
#endif
}

void MetricsCollector::inc_alerts_total(const std::string& level,
                                        const std::string& type,
                                        uint32_t n) {
#ifdef FENYUN_USE_PROMETHEUS
    impl_->f_alerts_total->Add({{"level", level}, {"type", type}}).Increment(n);
#else
    (void)level; (void)type; (void)n;
#endif
}

void MetricsCollector::inc_clickhouse_write_ok(uint64_t rows) {
#ifdef FENYUN_USE_PROMETHEUS
    impl_->f_ch_write_ok->Add({}).Increment(static_cast<double>(rows));
#else
    (void)rows;
#endif
}

void MetricsCollector::observe_http_request_latency_ms(const std::string& method,
                                                        const std::string& path,
                                                        double ms) {
#ifdef FENYUN_USE_PROMETHEUS
    static const auto buckets = prometheus::Histogram::BucketBoundaries{
        0.5, 1, 2, 5, 10, 25, 50, 100, 250, 500, 1000
    };
    impl_->f_http_latency->Add({{"method", method}, {"path", path}}, buckets).Observe(ms);
#else
    (void)method; (void)path; (void)ms;
#endif
}

void MetricsCollector::inc_http_request_total(const std::string& method,
                                               const std::string& path,
                                               int status_code) {
#ifdef FENYUN_USE_PROMETHEUS
    impl_->f_http_total->Add({
        {"method", method},
        {"path", path},
        {"status", std::to_string(status_code)}
    }).Increment();
#else
    (void)method; (void)path; (void)status_code;
#endif
}

void MetricsCollector::set_queue_approx_size(const std::string& queue_name, size_t size) {
#ifdef FENYUN_USE_PROMETHEUS
    impl_->f_queue_size->Add({{"queue", queue_name}}).Set(static_cast<double>(size));
#else
    (void)queue_name; (void)size;
#endif
}

}
